services:
  frontend:
    image: lets-get-couch-surfing-front-prod
    volumes:
      - ./frontend/:/usr/src/app
    container_name: lets-get-couch-surfing-front-prod
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080/api
  backend:
    image: lets-get-couch-surfing-back-prod
    environment:
      - PROD_DB_URL=postgresql://postgres:secret@db:5432/prod
    depends_on:
      - db
    container_name: lets-get-couch-surfing-back-prod
    # ports:
    #  - 3001:3001
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: prod
    ports:
      - "5432:5432"
    container_name: prod-db
    restart: always
    volumes:
      - db_prod_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend
volumes:
  db_prod_data:
    name: db_prod_data
    external: true
