services:
  frontend:
    image: lets-get-couch-surfing-front-dev
    volumes:
      - ./frontend/:/usr/src/app
    container_name: lets-get-couch-surfing-front-dev
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080/api
  backend:
    image: lets-get-couch-surfing-back-dev
    environment:
      - DEV_DB_URL=postgresql://postgres:secret@db:5432/postgres
    depends_on:
      - db
    container_name: lets-get-couch-surfing-back-dev
    # ports:
    #  - 3001:3001
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend
volumes:
  db_data:
