# fly.toml app configuration file generated for lets-get-couch-surfing on 2023-05-31T18:17:17+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lets-get-couch-surfing"
primary_region = "eze"

[env]
  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
