version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: prod
    ports:
      - "5432:5432"
    container_name: prod-db
    restart: always
    volumes:
      - db_prod_data:/var/lib/postgresql/data

volumes:
  db_prod_data:
    name: db_prod_data
