version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    image: lets-get-couch-surfing-back-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - DEV_DB_URL=postgresql://postgres:secret@db:5432/postgres # miks tää ei oo localhost:5432 vaan postgres:5432?
    ports:
      - 3001:3001
    command: npm run dev
    depends_on:
      - db
    container_name: lets-get-couch-surfing-back-dev

volumes:
  db_data:
