# A docker compose file for running the database only
# Can be used when running the app locally with only npm run dev

version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    container_name: db
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
