/// Here all rest requests to user routes for testing the app
post http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Test User",
  "username": "testuser10",
  "password": "secret"
}


###
// Here all rest requests to user routes for testing the app
post http://localhost:8080/api/api/users
Content-Type: application/json

{
  "name": "Test User",
  "username": "testuser100",
  "password": "secret"
}
###
get http://localhost:3001/api/users

###
get http://localhost:3001/api/users/dcb07b07-6307-4699-812f-147b4b51cb38

###

post http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Tester 2",
  "username": "testuser2",
  "password": "secret"
}