# docker-compose joka tekee seuraavat asiat

# käynnistää testitietokannan
# ajaa testit
# clean up the test environment after running the tests

# services:
# db-test:
# image: postgres
# if you set up the database here, you will always have two database instances running
# it would make a lot more sense to have the test database running only when running tests

# test:
# image: test
# luo Dockerfile joka ajaa testit ja käytä sitä edellä nimetyn imagen luomiseen
# kysymys: Pitäiskö ajaa kaikki testit tässä samassa vai erikseen e2e testit ja yksikkötestit?

# A docker compose file for running the database only
# Can be used when running the app locally with only npm run dev

version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    container_name: test-db
    restart: always
    volumes:
      - db_test_data:/var/lib/postgresql/data

volumes:
  db_test_data:
